# Generated by Django 5.0.3 on 2024-05-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='dislike',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
